name: Frontend checker, will punish for bad code ğŸª“ğŸ˜µâ€ğŸ’«
run-name: ${{ github.actor }} is starting sueta at the frontend code â˜ºï¸

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  pipeline:
    # Exclude renovate[bot] from triggering the workflow
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.JS ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'

      - name: Install yarn and dependencies ğŸ»
        run: |
          npm install --global yarn
          yarn install --immutable

      - name: Lint and Format ğŸ›«
        run: |
          yarn prettier:check
          yarn lint:eslint:check

      - name: Unit Testing ğŸ’€
        run: yarn test:unit

      - name: Build project ğŸ—ï¸
        run: yarn build

#  deploy:
#    needs: pipeline
#    if: success()
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Set Vercel Args
#        id: vercel_args
#        run: |
#          if [[ "${{ github.event_name }}" == "push" ]]; then
#            echo "::set-output name=args::--prod"
#          else
#            echo "::set-output name=args::"
#          fi
#
#
#      - name: Deploy Frontend
#        uses: amondnet/vercel-action@v20
#        with:
#          vercel-token: ${{ secrets.VERCEL_TOKEN }}
#          vercel-org-id: ${{ secrets.ORG_ID }}
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          vercel-project-id: ${{ secrets.PROJECT_ID }}
#          vercel-args: '--prod'
